name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  format-and-lint:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Format
        run: npm run format
      - name: Lint
        run: npm run lint:strict

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Check types
        run: npm run ts:check
      - name: Test
        run: npm run test
